# Initialization

In [2]:
import numpy as np
import torch

# Basic algebra

In [41]:
A = 1; B = 2
A + B

3

In [17]:
A - B

-1

In [18]:
A * B

2

In [19]:
A / B

0.5

# Constants

In [22]:
1j # imaginary number

1j

In [23]:
np.pi

3.141592653589793

In [24]:
np.e

2.718281828459045

In [29]:
#1 / 0; -1 / 0; 0 /  # All give rise to the ZeroDivisionError

In [68]:
A = 1; B = 2
A + B

3

# Vectors and matrices in Torch

In [37]:
torch.tensor([1, 2, 3])  # row vector

tensor([1, 2, 3])

In [40]:
torch.tensor([[1], [2], [3]])  # column vector

tensor([[1],
        [2],
        [3]])

In [163]:
torch.tensor([1, 2, 3]).reshape(3,1)

tensor([[1],
        [2],
        [3]])

In [65]:
torch.tensor([[1, 2],[3, 4]])

tensor([[1, 2],
        [3, 4]])

In [66]:
torch.arange(1,3)

tensor([1, 2])

In [62]:
torch.arange(1,11,3)

tensor([ 1,  4,  7, 10])

In [64]:
torch.arange(1,3,2)

tensor([1])

In [71]:
torch.arange(1,-10,-3)

tensor([ 1, -2, -5, -8])

In [72]:
torch.rand((3,2))

tensor([[0.0973, 0.0300],
        [0.4926, 0.1014],
        [0.9620, 0.5794]])

In [73]:
torch.ones((3,2))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [74]:
torch.zeros((3,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [75]:
torch.rand(3)

tensor([0.4958, 0.1771, 0.1898])

In [76]:
torch.ones(3)

tensor([1., 1., 1.])

In [77]:
torch.zeros(3)

tensor([0., 0., 0.])

In [84]:
A = torch.rand((3,2,3))
A

tensor([[[0.2209, 0.0397, 0.1170],
         [0.3025, 0.0045, 0.1658]],

        [[0.1966, 0.4569, 0.8152],
         [0.0137, 0.1497, 0.8594]],

        [[0.1503, 0.0183, 0.3470],
         [0.0729, 0.7303, 0.1676]]])

In [92]:
A[:,:,0]

tensor([[0.2209, 0.3025],
        [0.1966, 0.0137],
        [0.1503, 0.0729]])

In [89]:
A[:,0,:]

tensor([[0.2209, 0.0397, 0.1170],
        [0.1966, 0.4569, 0.8152],
        [0.1503, 0.0183, 0.3470]])

In [90]:
A[1,:,:]

tensor([[0.1966, 0.4569, 0.8152],
        [0.0137, 0.1497, 0.8594]])

In [94]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [96]:
torch.eye(3,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]])

In [97]:
torch.eye(4,2)

tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

# Matrix operations

In [161]:
A = torch.rand(3,2); B = torch.rand(2,4)

In [104]:
A @ B  # matrix multiplication

tensor([[0.7663, 0.7585, 1.3436, 1.2368],
        [0.2916, 0.5372, 0.6533, 0.6767],
        [0.1787, 0.0526, 0.2424, 0.1854]])

In [109]:
A

tensor([[0.3370, 0.2865],
        [0.5876, 0.3923],
        [0.8759, 0.5271]])

In [114]:
B = torch.rand((3,2))
B

tensor([[0.8970, 0.9375],
        [0.8873, 0.8277],
        [0.4544, 0.1608]])

In [115]:
A + B  # element-wise 

tensor([[1.2340, 1.2240],
        [1.4749, 1.2200],
        [1.3303, 0.6879]])

In [116]:
A - B  # element-wise 

tensor([[-0.5599, -0.6510],
        [-0.2997, -0.4353],
        [ 0.4215,  0.3663]])

In [117]:
A * B  # element-wise 

tensor([[0.3023, 0.2686],
        [0.5214, 0.3247],
        [0.3980, 0.0848]])

In [119]:
A / B  # element-wise 

tensor([[0.3757, 0.3056],
        [0.6623, 0.4740],
        [1.9277, 3.2780]])

In [128]:
C = A @ torch.pinverse(B)  # for square matrices use torch.inverse
C @ B - A

tensor([[-8.9407e-08, -2.9802e-08],
        [-1.1921e-07, -5.9605e-08],
        [-1.1921e-07,  0.0000e+00]])

# Size commands

In [160]:
A = torch.rand(3,2)

In [134]:
A.shape

torch.Size([3, 2])

In [136]:
A.size()

torch.Size([3, 2])

In [138]:
A.size(0)  # first dimension

3

In [140]:
A.size(1)  # second dimension

2

In [141]:
A.numel()

6

In [143]:
torch.rand((3,1))  # vector

tensor([[0.5315],
        [0.5167],
        [0.8686]])

# Transpose and Hermitian

In [159]:
A = torch.rand(3,2) + 1j * torch.rand(3,2)
A

tensor([[0.2106+0.6003j, 0.2996+0.8188j],
        [0.5329+0.7501j, 0.7162+0.2828j],
        [0.0792+0.4387j, 0.2753+0.4403j]])

In [150]:
A.T  # transpose

tensor([[0.9869+0.9470j, 0.2234+0.0486j, 0.1996+0.3556j],
        [0.1677+0.6015j, 0.8633+0.4024j, 0.5453+0.6878j]])

In [151]:
A.conj().T  # conjugate transpose

tensor([[0.9869-0.9470j, 0.2234-0.0486j, 0.1996-0.3556j],
        [0.1677-0.6015j, 0.8633-0.4024j, 0.5453-0.6878j]])

In [156]:
np.conj(1j) # complex conjugation for a number

-1j

# Accessing the elements and submatrices of matrices

In [193]:
A = torch.rand(5,5)
A

tensor([[0.1190, 0.0936, 0.0311, 0.2771, 0.8786],
        [0.4235, 0.2326, 0.0937, 0.3965, 0.3524],
        [0.0645, 0.5305, 0.0639, 0.5298, 0.9652],
        [0.3126, 0.0595, 0.8084, 0.9274, 0.1910],
        [0.1456, 0.5670, 0.6869, 0.4153, 0.1078]])

In [194]:
A[1,3]

tensor(0.3965)

In [195]:
A[:,2]

tensor([0.0311, 0.0937, 0.0639, 0.8084, 0.6869])

In [196]:
A[:,:]

tensor([[0.1190, 0.0936, 0.0311, 0.2771, 0.8786],
        [0.4235, 0.2326, 0.0937, 0.3965, 0.3524],
        [0.0645, 0.5305, 0.0639, 0.5298, 0.9652],
        [0.3126, 0.0595, 0.8084, 0.9274, 0.1910],
        [0.1456, 0.5670, 0.6869, 0.4153, 0.1078]])

In [197]:
A.reshape(-1,1)  # -1 is used to infer the first dimention

tensor([[0.1190],
        [0.0936],
        [0.0311],
        [0.2771],
        [0.8786],
        [0.4235],
        [0.2326],
        [0.0937],
        [0.3965],
        [0.3524],
        [0.0645],
        [0.5305],
        [0.0639],
        [0.5298],
        [0.9652],
        [0.3126],
        [0.0595],
        [0.8084],
        [0.9274],
        [0.1910],
        [0.1456],
        [0.5670],
        [0.6869],
        [0.4153],
        [0.1078]])

In [198]:
A[0:3,1:3]  # first three rows of the second and third columns

tensor([[0.0936, 0.0311],
        [0.2326, 0.0937],
        [0.5305, 0.0639]])

In [199]:
A[3:,3:]  # the last two rows and colums

tensor([[0.9274, 0.1910],
        [0.4153, 0.1078]])

In [200]:
A[4,4] = 1.0  # reassigning the value
A

tensor([[0.1190, 0.0936, 0.0311, 0.2771, 0.8786],
        [0.4235, 0.2326, 0.0937, 0.3965, 0.3524],
        [0.0645, 0.5305, 0.0639, 0.5298, 0.9652],
        [0.3126, 0.0595, 0.8084, 0.9274, 0.1910],
        [0.1456, 0.5670, 0.6869, 0.4153, 1.0000]])

In [201]:
A[0:3,1:3] = 1.0  # reassigning multiple values

In [202]:
A

tensor([[0.1190, 1.0000, 1.0000, 0.2771, 0.8786],
        [0.4235, 1.0000, 1.0000, 0.3965, 0.3524],
        [0.0645, 1.0000, 1.0000, 0.5298, 0.9652],
        [0.3126, 0.0595, 0.8084, 0.9274, 0.1910],
        [0.1456, 0.5670, 0.6869, 0.4153, 1.0000]])

In [203]:
A[:,:] = 0
A

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [205]:
A = torch.rand(3,3)
A

tensor([[0.6118, 0.9188, 0.5373],
        [0.4556, 0.0500, 0.3171],
        [0.0121, 0.6689, 0.6308]])

In [208]:
A[0]  # linear index

tensor([0.6118, 0.9188, 0.5373])

In [209]:
A = torch.rand(3,2,3)
A

tensor([[[0.3064, 0.4417, 0.5417],
         [0.3349, 0.6171, 0.0575]],

        [[0.9628, 0.2418, 0.7029],
         [0.7779, 0.9182, 0.5918]],

        [[0.8060, 0.8862, 0.7229],
         [0.4883, 0.7391, 0.2973]]])

In [211]:
A[0]  # consistency for the multidimnsional array

tensor([[0.3064, 0.4417, 0.5417],
        [0.3349, 0.6171, 0.0575]])

# Reshape and permute matrices

In [225]:
A = torch.arange(6)
A

tensor([0, 1, 2, 3, 4, 5])

In [226]:
B = A.reshape(3,2)
B

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [235]:
B.permute(1,0)  # same as transpose for matrices

tensor([[0, 2, 4],
        [1, 3, 5]])

# Sum and product

In [249]:
A

tensor([0, 1, 2, 3, 4, 5])

In [250]:
B

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [237]:
A.sum()

tensor(15)

In [240]:
B.sum(0)  # summing rows

tensor([6, 9])

In [241]:
B.sum(1)  # summing columns

tensor([1, 5, 9])

In [243]:
B.sum()  # summing all the elements

tensor(15)

In [246]:
B.prod()  # product of all the elements

tensor(0)

In [253]:
B.prod(0)  # product along the rows

tensor([ 0, 15])

In [252]:
B.prod(1)  # product along the columns

tensor([ 0,  6, 20])

# Eigenvalues and eigenvectors

In [323]:
A = torch.rand(3, 3)
A = (A + A.T) / 2  # symmetrize
A

tensor([[0.0257, 0.6559, 0.6388],
        [0.6559, 0.9395, 0.4403],
        [0.6388, 0.4403, 0.0685]])

In [274]:
D, _ = A.eig()  # eigenvalues
D  # contains 2 columns: Re, Img

tensor([[1.5927, 0.0000],
        [0.2797, 0.0000],
        [0.0465, 0.0000]])

In [279]:
D, V = A.eig(eigenvectors=True)  # eigenvalues and eigenvectors

In [280]:
D[:,0] + 1j*D[:,1]

tensor([1.5927+0.j, 0.2797+0.j, 0.0465+0.j])

In [278]:
V

tensor([[ 0.7344,  0.6548, -0.1784],
        [ 0.5144, -0.7085, -0.4832],
        [ 0.4428, -0.2631,  0.8571]])

In [298]:
V @ D.sum(1).diag() @ V.T - A  # should be close to zero

tensor([[3.5763e-07, 1.4901e-07, 2.9802e-07],
        [1.4901e-07, 1.7881e-07, 1.7881e-07],
        [2.9802e-07, 1.7881e-07, 2.0862e-07]])

In [300]:
V.T @ V  # left unitarity

tensor([[1.0000e+00, 4.1032e-08, 8.7385e-08],
        [4.1032e-08, 1.0000e+00, 2.3708e-07],
        [8.7385e-08, 2.3708e-07, 1.0000e+00]])

In [302]:
V @ V.T  # right unitarity

tensor([[ 1.0000e+00,  0.0000e+00,  2.5332e-07],
        [ 0.0000e+00,  1.0000e+00, -8.9407e-08],
        [ 2.5332e-07, -8.9407e-08,  1.0000e+00]])

# Singular value decomposition

## Square matrices

In [350]:
A = torch.rand(3, 3)
A

tensor([[0.1216, 0.6980, 0.4132],
        [0.8877, 0.9728, 0.5515],
        [0.1946, 0.1867, 0.5522]])

In [351]:
U,S,V = A.svd()

In [352]:
S

tensor([1.6782, 0.4036, 0.3310])

In [353]:
U @ S.diag() @ V.T - A  # should be zero up to numerical precision

tensor([[-1.6391e-07, -1.1921e-07, -8.9407e-08],
        [-2.9802e-07, -4.1723e-07, -1.7881e-07],
        [-7.4506e-08, -1.0431e-07,  0.0000e+00]])

In [354]:
U @ U.T  # identity

tensor([[ 1.0000e+00, -5.9908e-08,  4.0297e-08],
        [-5.9908e-08,  1.0000e+00, -1.0296e-08],
        [ 4.0297e-08, -1.0296e-08,  1.0000e+00]])

In [355]:
U.T @ U

tensor([[ 1.0000e+00,  8.9407e-08, -2.9802e-08],
        [ 8.9407e-08,  1.0000e+00, -5.9605e-08],
        [-2.9802e-08, -5.9605e-08,  1.0000e+00]])

In [356]:
V @ V.T

tensor([[ 1.0000e+00, -1.1921e-07, -1.4901e-08],
        [-1.1921e-07,  1.0000e+00, -2.9802e-08],
        [-1.4901e-08, -2.9802e-08,  1.0000e+00]])

In [357]:
V.T @ V

tensor([[ 1.0000e+00,  2.9046e-08, -4.6611e-08],
        [ 2.9046e-08,  1.0000e+00, -1.8797e-08],
        [-4.6611e-08, -1.8797e-08,  1.0000e+00]])

## Rectangular matrices

In [414]:
A = torch.rand(4,3)
A

tensor([[0.8846, 0.7998, 0.7399],
        [0.1341, 0.4003, 0.0178],
        [0.3396, 0.5908, 0.5144],
        [0.3041, 0.9777, 0.8650]])

In [459]:
U, S, V = A.svd(some=False)  # return non-reduced svd. 
                             # If the last two dimensions of input are m and n, 
                             # then the returned U and V matrices will contain 
                             # only min(n, m) orthonormal columns.
                             # In the matrix is tall, the reduced case will 
                             # return non-zero singular values.

In [478]:
U @ U.T  # unitary

tensor([[ 1.0000e+00, -4.8429e-08,  0.0000e+00, -8.9407e-08],
        [-4.8429e-08,  1.0000e+00,  1.6764e-07,  7.4506e-08],
        [ 0.0000e+00,  1.6764e-07,  1.0000e+00, -8.9407e-08],
        [-8.9407e-08,  7.4506e-08, -8.9407e-08,  1.0000e+00]])

In [477]:
U.T @ U  # unitary

tensor([[ 1.0000e+00,  1.7881e-07, -4.0978e-08, -4.4703e-08],
        [ 1.7881e-07,  1.0000e+00,  7.8231e-08,  0.0000e+00],
        [-4.0978e-08,  7.8231e-08,  1.0000e+00, -1.5832e-07],
        [-4.4703e-08,  0.0000e+00, -1.5832e-07,  1.0000e+00]])

In [479]:
V @ V.T

tensor([[ 1.0000e+00,  2.6077e-08,  3.7253e-08],
        [ 2.6077e-08,  1.0000e+00, -1.4901e-07],
        [ 3.7253e-08, -1.4901e-07,  1.0000e+00]])

In [480]:
V.T @ V

tensor([[1.0000e+00, 8.7481e-08, 3.3118e-08],
        [8.7481e-08, 1.0000e+00, 1.6183e-09],
        [3.3118e-08, 1.6183e-09, 1.0000e+00]])

In [487]:
U[:,:3] @ S.diag() @ V.T - A  # Remeber, last column of U 
                              # corresponds to singular value S=0

tensor([[ 0.0000e+00,  0.0000e+00,  2.3842e-07],
        [ 0.0000e+00, -5.9605e-08,  7.4506e-08],
        [-5.9605e-08, -1.7881e-07, -5.9605e-08],
        [ 2.9802e-08, -2.9802e-07, -1.1921e-07]])

# QR decomposition

In [489]:
A = torch.rand(4,3)

In [503]:
Q, R = A.qr(some=False)  # A = Q*R
                         # By default, returns reduced decomposition
                         # unless some=False

In [504]:
Q, R

(tensor([[-0.5335,  0.2618, -0.2260, -0.7718],
         [-0.1298, -0.9553, -0.1985, -0.1762],
         [-0.3316,  0.1171, -0.7910,  0.5006],
         [-0.7671, -0.0710,  0.5327,  0.3502]]),
 tensor([[-1.0319, -1.0586, -1.3257],
         [ 0.0000, -0.3614, -0.2927],
         [ 0.0000,  0.0000, -0.7184],
         [ 0.0000,  0.0000,  0.0000]]))

In [505]:
Q @ R - A  # close to zero

tensor([[-5.9605e-08, -1.7881e-07, -2.3842e-07],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 2.9802e-08,  0.0000e+00, -5.9605e-08],
        [ 0.0000e+00, -5.9605e-08, -1.1921e-07]])

In [506]:
Q.T @ Q

tensor([[ 1.0000e+00,  5.9605e-08, -2.9802e-08, -1.7881e-07],
        [ 5.9605e-08,  1.0000e+00, -1.4901e-08,  4.4703e-08],
        [-2.9802e-08, -1.4901e-08,  1.0000e+00,  2.9802e-08],
        [-1.7881e-07,  4.4703e-08,  2.9802e-08,  1.0000e+00]])

In [507]:
Q @ Q.T

tensor([[ 1.0000e+00,  1.4901e-08,  0.0000e+00, -8.9407e-08],
        [ 1.4901e-08,  1.0000e+00, -1.4901e-08,  3.7253e-09],
        [ 0.0000e+00, -1.4901e-08,  1.0000e+00,  1.4901e-08],
        [-8.9407e-08,  3.7253e-09,  1.4901e-08,  1.0000e+00]])

# Time counter

In [509]:
from timeit import default_timer as timer

In [510]:
start = timer()
torch.rand(10,10)*torch.rand(10,10)
timer() - start

0.0005360590002965182

In [511]:
A.masked_select(A < 0.1)

tensor([])

# Logical variables and operations

In [520]:
A = torch.rand(4,3)
A

tensor([[0.8390, 0.8890],
        [0.4356, 0.4605],
        [0.9093, 0.7390]])

In [522]:
mask = A.ge(0.5)
mask

tensor([[ True,  True],
        [False, False],
        [ True,  True]])

In [524]:
A.masked_select(mask)  # the vector of elements of A larger than 0.5

tensor([0.8390, 0.8890, 0.9093, 0.7390])